# Generated by Django 4.0.5 on 2022-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Asignatura', models.CharField(max_length=50)),
                ('nombre_asignatura', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Estudiante', models.CharField(max_length=100)),
                ('id_Asignatura', models.CharField(max_length=100)),
                ('puntuacion', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.CharField(max_length=5)),
                ('nom_curso', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Estudiante', models.CharField(max_length=50)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstudianteProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Estudiante', models.CharField(max_length=100)),
                ('id_Profesor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Profesor', models.CharField(max_length=50)),
                ('apellido_1', models.CharField(max_length=100)),
                ('apellido_2', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
