# Generated by Django 4.0.5 on 2022-06-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id_curso',
            field=models.CharField(max_length=50),
        ),
    ]
