# Generated by Django 4.0.5 on 2022-06-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_domicilio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domicilio',
        ),
    ]
