# Generated by Django 4.0.5 on 2022-06-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_domicilio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='id_Asignatura',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='id_curso',
        ),
    ]
