# Generated by Django 4.0.5 on 2022-06-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_asignatura_id_asignatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nom_curso',
        ),
    ]
