# Generated by Django 4.0.5 on 2022-06-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_curso_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calificaciones',
            old_name='id_Asignatura',
            new_name='Asignatura',
        ),
        migrations.RenameField(
            model_name='calificaciones',
            old_name='id_Estudiante',
            new_name='Estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id_Estudiante',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='id_Profesor',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='Profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.ManyToManyField(to='webapp.curso'),
        ),
    ]
