# Generated by Django 4.0.5 on 2022-07-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_rename_id_asignatura_calificaciones_asignatura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='Asignatura',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Asignatura',
            field=models.ManyToManyField(to='webapp.asignatura'),
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='Estudiante',
        ),
        migrations.AddField(
            model_name='calificaciones',
            name='Estudiante',
            field=models.ManyToManyField(to='webapp.estudiante'),
        ),
    ]
