# Generated by Django 4.0.5 on 2022-07-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_profesor_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.asignatura'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
