# Generated by Django 4.0.5 on 2022-07-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_estudiante_asignatura_alter_estudiante_apellido_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='asignatura',
            field=models.ManyToManyField(to='webapp.asignatura'),
        ),
    ]
