# Generated by Django 4.0.5 on 2022-07-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_remove_estudiante_asignatura_estudiante_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='curso',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
