# Generated by Django 4.0.5 on 2022-07-06 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_estudiante_curso_delete_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nota',
            field=models.FloatField(default=0),
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.asignatura'),
        ),
    ]
